project:
  type: website
  render:
    - "*.md"
    - "*.Rmd"
    - "*.qmd"
    - "*.ipynb"
  output-dir: .

website:
  title: "Ampile"
  navbar:
    right:
      - text: Source code
        icon: github
        href: https://github.com/chenh19/Ampile

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
    include-after-body: _footer.html
